/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code;

import org.junit.Test;
import java.math.BigInteger;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class AppTest {

    @Test
    public void stringShouldBecomeStringAgain(){

    }




}
